[package]
name = "zoomout"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
trust-dns-server = "0.22"
trust-dns-proto = "0.22"
anyhow = "1.0"
regex = "1"
log = "0.4"
env_logger = "0.9"
base64 = "0.21"
